### ISSUE TITLE
warning in ruby 2.7.0

### ISSUE THREAD

**Issue by huobazi** [newrelic/rpm#307] opened 2019-12-26 12:04 UTC
```bash
/Users/mw82/.gem/ruby/2.7.0/gems/newrelic_rpm-6.7.0.359/lib/new_relic/dependency_detection.rb:118: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
```

**Comment by mwlang** [comment] 2019-12-27 13:38
Thank you for @houbazi for taking the time to report this issue.  I'm closing as this is a duplicate of #305.  The next release of the agent will resolve these warnings.

**Closed by mwlang** 2019-12-27 13:38 UTC
Labels: duplicate
